Web2/Web2/Areas/Admin/Controllers/QuanLyLSPController.cs
using CellPhoneConnection;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web2.Areas.Admin.Models;
using Web2.Areas.Admin.Models.BUS;

namespace Web2.Areas.Admin.Controllers
{
    public class QuanLyLSPController : Controller
    {
        // GET: Admin/QuanLyLSP
        public ActionResult Index(int page = 1, int pageSize = 4)
        {
            var ds = QuanLyLoaiSanPhamBUS.DanhSach().ToPagedList(page, pageSize);
            return View(ds);
        }

        // GET: Admin/QuanLyLSP/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/QuanLyLSP/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/QuanLyLSP/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham item)
        {
            try
            {
                // TODO: Add insert logic here
                QuanLyLoaiSanPhamBUS.Them1LSP(item);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/QuanLyLSP/Edit/5
        public ActionResult Edit(int id)
        {
            return View(QuanLyLoaiSanPhamBUS.ChiTIet(id));
        }

        // POST: Admin/QuanLyLSP/Edit/5
        [HttpPost]
        public ActionResult Edit(LoaiSanPham item)
        {
            try
            {
                // TODO: Add update logic here
                QuanLyLoaiSanPhamBUS.CapNhat1LSP(item);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/QuanLyLSP/Deny/5
        public ActionResult Deny(int id)
        {
            QuanLyLoaiSanPhamBUS.Deny(id);
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        // GET: Admin/QuanLyLSP/Allow/5
        public ActionResult Allow(int id)
        {
            QuanLyLoaiSanPhamBUS.Allow(id);
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
        // POST: Admin/QuanLyLSP/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web2/Web2/Areas/Admin/Views/QuanLyLSP/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}


<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Thêm mới 1 Loai san pham</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Create", "QuanLyLSP", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenLoaiSanPham">Tên loai san pham:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenLoaiSanPham" name="a_TenLoaiSP" placeholder="Nhập LSP tại đây!">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Hoàn thành!</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyLSP/Edit.cshtml
@model CellPhoneConnection.LoaiSanPham
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Chinh sua 1 Loai san pham</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Edit", "QuanLyLSP", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id">ID Loai san pham:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id" name="a_IDLoaiSP" value="@Model.a_IDLoaiSP" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenLoaiSanPham">Tên Nhà sản xuất:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenLoaiSanPham" name="a_TenLoaiSP" value="@Model.a_TenLoaiSP">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TinhTrang">Tinh trang:</label>
                                    <div class="col-sm-10">

                                        <select id="TinhTrang" name="a_TinhTrang" required>
                                            @if (Model.a_TinhTrang == 0)
                                            {
                                                <option value="0" selected>Hien thi</option>
                                                <option value="1">An</option>
                                            }
                                            else
                                            {
                                                <option value="1" selected>An</option>
                                                <option value="0">Hien thi</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Cập nhật</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyLSP/Index.cshtml
@model PagedList.IPagedList<CellPhoneConnection.LoaiSanPham>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}

<div id="page-wrapper" style="min-height: 444px;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Quan ly Loai san pham</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <button>
                        <a href="@Url.Action("Create","QuanLyLSP")">Them moi!</a>
                    </button>
                </div>
                <div class="panel-heading">
                    Danh muc:
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                    <thead>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>ID</td>
                                            <td>Ten loai san pham</td>
                                            <td>Tinh trang</td>
                                        </tr>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="gradeA odd" role="row">
                                                <td>@item.a_IDLoaiSP</td>
                                                <td>@item.a_TenLoaiSP</td>
                                                <td>@item.a_TinhTrang</td>
                                                <td>
                                                    <button>
                                                        <a href="@Url.Action("Edit", "QuanLyLSP", new { id = @item.a_IDLoaiSP })">Edit</a>
                                                    </button>
                                                </td>
                                                <td>
                                                    <button><a href="@Url.Action("Deny", "QuanLyLSP", new { id = @item.a_IDLoaiSP })">Deny</a></button>                                                
                                                </td>
                                                <td>
                                                    <button><a href="@Url.Action("Allow", "QuanLyLSP", new { id = @item.a_IDLoaiSP })">Allow</a></button>
                                                </td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                    </div>
                    <!-- /.table-responsive -->

                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <!-- /.row -->
</div>