Web2/Web2/Areas/Admin/Controllers/QuanLyNSXController.cs
using CellPhoneConnection;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web2.Areas.Admin.Models;

namespace Web2.Areas.Admin.Controllers
{
    public class QuanLyNSXController : Controller
    {
        // GET: Admin/QuanLyNhaSanXuat
        public ActionResult Index(int page = 1, int pageSize = 4)
        {
            var ds = QuanLyNhaSanXuatBUS.DanhSach().ToPagedList(page, pageSize);
            return View(ds);
        }

        // GET: Admin/QuanLyNhaSanXuat/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/QuanLyNhaSanXuat/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/QuanLyNhaSanXuat/Create
        [HttpPost]
        public ActionResult Create(NhaSanXuat nsx)
        {
            try
            {
                // TODO: Add insert logic here
                QuanLyNhaSanXuatBUS.Them1NSX(nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/QuanLyNhaSanXuat/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/QuanLyNhaSanXuat/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/QuanLyNhaSanXuat/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/QuanLyNhaSanXuat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web2/Web2/Areas/Admin/Views/QuanLyNSX/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Thêm mới 1 Nhà sản xuất</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Create", "QuanLyNSX", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tên Nhà sản xuất:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenNhaSanXuat" name="a_TenNhaSX" placeholder="Nhập NSX tại đây!">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Hoàn thành!</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyNSX/Delete.cshtml
@model CellPhoneConnection.NhaSanXuat
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Nhà sản xuất sẽ bị ẩn khỏi hiển thị</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Delete", "QuanLyNSX", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id">ID Nha san xuat:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id" name="a_IDNhaSX" value="@Model.a_IDNhaSX" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tên Nhà sản xuất:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenNhaSanXuat" name="a_TenNhaSX" value="@Model.a_TenNhaSX" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tinh trang:</label>
                                    <div class="col-sm-10">

                                        <select id="TinhTrang" name="a_TinhTrang" required>
                                            @if (Model.a_TinhTrang == 0)
                                            {
                                                <option value="0" selected>Hien thi</option>
                                                <option value="1">An</option>
                                            }
                                            else
                                            {
                                                <option value="1" selected>An</option>
                                                <option value="0">Hien thi</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Cập nhật</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyNSX/Details.cshtml
@model CellPhoneConnection.NhaSanXuat
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Chinh sua 1 Nha San Xuat</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Edit", "QuanLyNSX", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id">ID Nha san xuat:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id" name="a_IDNhaSX" value="@Model.a_IDNhaSX" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tên Nhà sản xuất:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenNhaSanXuat" name="a_TenNhaSX" value="@Model.a_TenNhaSX">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Cập nhật</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyNSX/Edit.cshtml
@model CellPhoneConnection.NhaSanXuat
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Chinh sua 1 Nha San Xuat</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Thông tin chi tiết:</a>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            @using (Html.BeginForm("Edit", "QuanLyNSX", FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="id">ID Nha san xuat:</label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="id" name="a_IDNhaSX" value="@Model.a_IDNhaSX" readonly>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tên Nhà sản xuất:</label>
                                    <div class="col-sm-10">
                                        <input type="text" required class="form-control" id="TenNhaSanXuat" name="a_TenNhaSX" value="@Model.a_TenNhaSX">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-2" for="TenNhaSanXuat">Tinh trang:</label>
                                    <div class="col-sm-10">

                                        <select id="TinhTrang" name="a_TinhTrang" required>
                                            @if (Model.a_TinhTrang == 0)
                                            {
                                                <option value="0" selected>Hien thi</option>
                                                <option value="1">An</option>
                                            }
                                            else
                                            {
                                                <option value="1" selected>An</option>
                                                <option value="0">Hien thi</option>
                                            }
                                        </select>
                                        </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-default">Cập nhật</button>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web2/Web2/Areas/Admin/Views/QuanLyNSX/Index.cshtml
@model PagedList.IPagedList<CellPhoneConnection.NhaSanXuat>
@using PagedList.Mvc;
@{
    ViewBag.Title = "_DanhSachNhaSanXuat";
    Layout = "~/Areas/Admin/Views/Shared/_MainLayoutForAdmin.cshtml";
}



<div id="page-wrapper" style="min-height: 444px;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">User management</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#">Add user!</a>
                </div>
                <div class="panel-heading">
                    Edit user!
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-striped table-bordered table-hover dataTable no-footer dtr-inline" id="dataTables-example" role="grid" aria-describedby="dataTables-example_info" style="width: 100%;">
                                    <thead>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr class="gradeA odd" role="row">
                                                <td>@item.a_IDNhaSX</td>
                                                <td>@item.a_TenNhaSX</td>
                                                <td><a href="#">Edit</a></td>
                                                <td><a href="#">Remove</a></td>
                                            </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                    </div>
                    <!-- /.table-responsive -->

                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <!-- /.row -->
</div>